# This playbook clean the package cache of Alpine Linux hosts.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: all

  tasks:
  - name: clean package cache
    command: /sbin/apk cache clean
