---
- name: Alpine dynamic MOTD generator
  hosts: all
  vars:
    placeholder: "daily"
    file: "motd-script"
    md5sum: "c0a59404b013ff89521279a95d097a8b"

  tasks:
    - name: Run a command with sudo
      become: yes
      become_method: sudo
      command: whoami
      register: result

    - name: Output result
      debug:
        msg: "Command executed as: {{ result.stdout }}"

    - name: Check for presence of crond service
      command: rc-service crond status
      register: crond_status
      failed_when: crond_status.failed
      ignore_errors: yes

    - name: Fail if crond service is not present
      fail:
        msg: "crond service is not present"
      when: crond_status.failed

    - name: Check if crond service is running
      command: rc-service crond status
      register: crond_running
      failed_when: "'started' not in crond_running.stdout"
      ignore_errors: yes

    - name: Output of crond_running
      debug:
        msg: "{{crond_running}}"

    - name: Start crond service if not running
      command: rc-service crond start
      when: "'started' not in crond_running.stdout"
      register: crond_start
      failed_when: crond_start.failed

    - name: Check original Alpine motd file against md5sum
      shell: "echo '{{md5sum}}  /etc/motd' | md5sum --check --strict"
      register: motd_md5sum
      failed_when: motd_md5sum.failed
      ignore_errors: yes

    - name: Output md5sum of the original Alpine motd file
      debug:
        msg: "{{motd_md5sum}}"
      when: motd_md5sum.failed

    - name: Backup original Alpine motd file if md5sum does match
      command: /usr/bin/sudo /bin/cp --force /etc/motd /etc/motd.bak
      when: not motd_md5sum.failed
      register: motd_backup
      failed_when: motd_backup.failed

    - name: Fail if motd backup fails
      fail:
        msg: "Backup of the original Alpine motd file failed"
      when: motd_backup.failed

    - name: Check for presence of motd script
      stat:
        path: /etc/periodic/{{ placeholder }}/{{ file }}
      register: motd_stat

    - name: Output of motd_stat
      debug:
        msg: "{{motd_stat}}"

    - name: Create motd script if not present
      command: /usr/bin/sudo /bin/touch /etc/periodic/{{ placeholder }}/{{ file }}
      when: not motd_stat.stat.exists
      register: motd_script

    - name: Output of motd_script
      debug:
        msg: "{{motd_script}}"

    - name: Ensure correct file permissions
      command: /usr/bin/sudo /bin/chmod 0755 /etc/periodic/{{ placeholder }}/{{ file }}
      when: not motd_script.failed

    - name: Check execution of the file
      command: /usr/bin/sudo run-parts --test /etc/periodic/{{ placeholder }}
      register: run_parts_test
      failed_when: run_parts_test.failed
      ignore_errors: yes

    - name: Fail if run-parts test fails
      fail:
        msg: "run-parts test failed"
      when: run_parts_test.failed
