# This playbook updates all Alpine Linux hosts and initialize a reboot.
#
# Copyright (c) 2013-2022 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: Alpine Maintenance update
  hosts: web

  tasks:
  - name: update package list
    ansible.builtin.command:
      cmd: /sbin/apk update -v
    become: yes

  - name: update all packages
    ansible.builtin.command:
      cmd: /sbin/apk upgrade -U -a -v
    become: yes

  - name: reboot system
    ansible.builtin.command:
      cmd: /sbin/reboot -d 5 --simulate
    become: yes
