# This playbook updates all Alpine Linux hosts and initialize a reboot.
#
# Copyright (c) 2013-2022 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: Alpine Maintenance update
  hosts: alpine

  tasks:
  - name: Ensure group "wheel" exists
    ansible.builtin.group:
      name: wheel
      state: present
    
  - name: update package list
    ansible.builtin.command:
      cmd: /usr/bin/sudo /sbin/apk update -v
    #become: yes
    #become_method: sudo

  - name: update all packages
    ansible.builtin.command:
      cmd: /usr/bin/sudo /sbin/apk upgrade -U -a -v
    #become: yes
    #become_method: sudo

#  - name: reboot system
#    ansible.builtin.command:
#      cmd: /usr/bin/sudo /sbin/reboot -d 5
#    #become: yes
#    #become_method: sudo
