---
- name: Linux whoami check
  hosts: all

  tasks:
    - name: Run a command without sudo
      command: whoami
      register: result

    - name: Output result
      debug:
        msg: "Command executed as: {{ result.stdout }}"

    - name: Run a command with sudo
      become: yes
      become_method: sudo
      command: whoami
      register: result

    - name: Output result
      debug:
        msg: "Command executed as: {{ result.stdout }}"

    - name: Create motd script if not present
      become: yes
      become_method: sudo
      copy:
        content: |
          #!/bin/sh
          echo "Dynamic MOTD"
        dest: /etc/periodic/daily/test
        owner: root
        group: root
        mode: '0755'
